project_id = "fduusrbjqdrfuumtisrn"

[functions.api]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.change-user-password]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.send-templated-email]
verify_jwt = false

[functions.disable-user-2fa]
verify_jwt = false
